### ISSUE TITLE
Error in README

### ISSUE THREAD

**Issue by rdk-pmis** [siderisng/vue-remember-scroll-cache#1]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `vue-remember-scroll-cache@1.1.0` for the project I'm working on.

I noticed an error in the README.md

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/vue-remember-scroll-cache/README.md b/node_modules/vue-remember-scroll-cache/README.md
index 1849561..2450ead 100644
--- a/node_modules/vue-remember-scroll-cache/README.md
+++ b/node_modules/vue-remember-scroll-cache/README.md
@@ -52,7 +52,7 @@ In component script section:
 
 
 const prevPage = localStorage.getItem('v-remember-scroll-page')
-if (this.$products && this.$products.length > 0 && prevPage === window.location.hostname) {
+if (this.$products && this.$products.length > 0 && prevPage === window.location.pathname) {
       this.products = this.$products
 }
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by siderisng** [comment]
Hello! Thank you for your feedback, you're right this is a mistake, I will update the readme file accordingly 🙂

**Comment by siderisng** [comment]
readme updated
